[GitHubAE] Update to 1.1.4-71eee93b8961601b8bc06eb2182d9151 from 1.1.4-a0193cc447e66879f2e294bf7f90f620 Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (20887:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (20901:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (20853:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (20874:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (20942:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (20953:9)
│ ├─┬/repos/{owner}/{repo}/hooks
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (20439:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (20463:9)
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (20477:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (20562:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   ├─┬External Docs
│ │   │ └──[M] url (20915:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (20926:9)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-extra-repository-information
│ │           ├──[M] value (197575:9)
│ │           ├──[M] value (197575:9)
│ │           ├──[M] value (197575:9)
│ │           ├──[M] value (197575:9)
│ │           ├──[M] value (197575:9)
│ │           ├──[M] value (197575:9)
│ │           ├──[M] value (197575:9)
│ │           └──[+] value (197575:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   ├─┬External Docs
│ │   │ └──[M] url (20811:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (20840:9)
│ ├─┬/enterprises/{enterprise}/secret-scanning/alerts
│ │ └─┬GET
│ │   └──[-] parameters (200677:13)❌
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (20728:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (20744:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (20759:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (20797:9)
│ ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[-] value (196347:9)
│ │ └─┬PATCH
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[-] value (196358:9)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬alternative-response-with-repository-permissions
│ │           ├──[M] value (186523:9)
│ │           ├──[M] value (186523:9)
│ │           ├──[M] value (186523:9)
│ │           ├──[M] value (186523:9)
│ │           ├──[M] value (186523:9)
│ │           ├──[M] value (186523:9)
│ │           ├──[M] value (186523:9)
│ │           └──[+] value (186523:9)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (20576:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (20594:9)
│ │ ├─┬DELETE
│ │ │ ├─┬External Docs
│ │ │ │ └──[M] url (20701:14)
│ │ │ └─┬Extensions
│ │ │   └──[M] x-github (20712:9)
│ │ └─┬PATCH
│ │   ├─┬External Docs
│ │   │ └──[M] url (20609:14)
│ │   └─┬Extensions
│ │     └──[M] x-github (20689:9)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (188126:9)
│ ├─┬/repos/{owner}/{repo}/license
│ │ └─┬GET
│ │   └─┬Responses
│ │     └──[-] codes (201265:7)❌
│ └─┬/repos/{owner}/{repo}/actions/runs
│   └─┬GET
│     └─┬Responses
│       └─┬200
│         └─┬application/json
│           └─┬default
│             └──[M] value (188126:9)
├─┬pull-request-edited
│ └─┬POST
│   └──[M] description (41154:20)
└─┬Components
  ├──[-] parameters (200677:7)❌
  ├─┬repository-webhooks
  │ └──[-] properties (65523:9)❌
  ├─┬team-repository
  │ └──[+] properties (53644:9)
  ├─┬secret-scanning-alert
  │ └──[-] properties (63354:9)❌
  ├─┬organization-secret-scanning-alert
  │ └──[-] properties (49398:9)❌
  ├─┬webhook-team-deleted
  │ └─┬repository
  │   └──[-] properties (173545:13)❌
  ├─┬webhook-team-created
  │ └─┬repository
  │   └──[-] properties (172942:13)❌
  ├─┬webhook-fork
  │ └─┬forkee
  │   └─┬ALLOF
  │     └──[-] properties (78744:15)❌
  ├─┬webhook-issues-transferred
  │ └─┬changes
  │   └─┬new_repository
  │     └──[-] properties (98380:17)❌
  ├─┬webhook-team-removed-from-repository
  │ └─┬repository
  │   └──[-] properties (174816:13)❌
  ├─┬webhook-issues-opened
  │ └─┬changes
  │   └─┬old_repository
  │     └──[-] properties (94036:17)❌
  ├─┬webhook-team-added-to-repository
  │ └─┬repository
  │   └──[-] properties (172340:13)❌
  ├─┬webhook-push
  │ └─┬repository
  │   └──[-] properties (165445:13)❌
  ├─┬webhook-team-edited
  │ └─┬repository
  │   └──[-] properties (174212:13)❌
  └─┬job
    └─┬status
      └──[-] enum (54628:13)❌

Date: 11/07/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 46            | 2
webhooks         | 1             | 0
components       | 15            | 15
❌  17 Breaking changes out of 62
INFO: Modifications: 41
INFO: Removals: 18
INFO: Additions: 3
INFO: Breaking Removals: 16

ERROR: breaking changes discovered