[GitHubAE] Update to 1.1.4-ace9f7cb37c72ef370f972e57f690f88 from 1.1.4-74b23f69ab43292c32beada294158c1f Detected Schema changes:
├─┬Paths
│ ├──[-] path (12359:3)❌
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/environments
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (192133:9)
│ ├─┬/repos/{owner}/{repo}/environments/{environment_name}
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └─┬application/json
│ │ │       └─┬default
│ │ │         └──[M] value (192194:9)
│ │ └─┬PUT
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (192194:9)
│ ├─┬/orgs/{org}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (200502:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners
│ │ └─┬GET
│ │   └──[M] description (11824:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/downloads
│ │ └─┬GET
│ │   └──[M] description (11873:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/{runner_id}
│ │ ├─┬GET
│ │ │ └──[M] description (11989:20)
│ │ └─┬DELETE
│ │   └──[M] description (12023:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (200502:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (200502:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (200502:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (200502:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/admin/hooks/{hook_id}
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (200502:20)
│ │ ├─┬DELETE
│ │ │ └─┬Parameters
│ │ │   └──[M] description (200502:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/admin/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries/{delivery_id}/attempts
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/cancel
│ │ └─┬POST
│ │   └──[M] description (12329:20)
│ ├─┬/orgs/{org}/hooks/{hook_id}/deliveries/{delivery_id}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/actions/runners/remove-token
│ │ └─┬POST
│ │   └──[M] description (11947:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/tests
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/config
│ │ ├─┬GET
│ │ │ └─┬Parameters
│ │ │   └──[M] description (200502:20)
│ │ └─┬PATCH
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/pings
│ │ └─┬POST
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ ├─┬/repos/{owner}/{repo}/hooks/{hook_id}/deliveries
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (200502:20)
│ └─┬/repos/{owner}/{repo}/actions/runners/registration-token
│   └─┬POST
│     └──[M] description (11909:20)
├──check-run-requested-action
├──check-run-created
└─┬Components
  └─┬environment
    └─┬protection_rules
      └─┬Schema
        └─┬ANYOF
          └──[-] properties (58714:17)❌

Date: 09/25/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 34            | 1
components       | 1             | 1
❌  2 Breaking changes out of 35
INFO: Modifications: 33
INFO: Removals: 2
INFO: Breaking Removals: 2

ERROR: breaking changes discovered