[GitHubAE] Update to 1.1.4 (hash: 11d92732886bbbff23c7d59fc14aec97) from 1.1.4 (hash: 55bc2b5ac90592f60e22cc43c3bcbdb5) Detected Schema changes:
├─┬Paths
│ ├─┬/user/installations/{installation_id}/repositories
│ │ └─┬GET
│ │   └──[M] description (30265:20)
│ ├─┬/orgs/{org}/code-scanning/alerts
│ │ └─┬GET
│ │   └──[-] parameters (6569:15)❌
│ ├─┬/repos/{owner}/{repo}/code-scanning/alerts
│ │ └─┬GET
│ │   └──[-] parameters (16232:15)❌
│ ├─┬/user/installations
│ │ └─┬GET
│ │   └──[M] description (30210:20)
│ └─┬/search/issues
│   └─┬GET
│     └──[M] description (28054:20)
├──check-run-completed
├─┬github-app-authorization-revoked
│ └─┬POST
│   └──[M] summary (35812:16)
└─┬Components
  ├──[-] schemas (51505:7)❌
  └─┬app-permissions
    └──[M] description (46269:20)

Date: 06/20/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 5             | 2
webhooks         | 1             | 0
components       | 2             | 1
❌ 3 Breaking changes out of 8

ERROR: breaking changes discovered