[GitHubAE] Update to 1.1.4 (hash: ec8d62c96c21ee75ab5090ebcb0e8cb2) from 1.1.4 (hash: 641f344a7bc7bb9ea2648bec19e473d2) Detected Schema changes:
└─┬Components
  ├──[-] schemas (65901:7)❌
  ├──[-] schemas (65888:7)❌
  ├─┬webhook-secret-scanning-alert-reopened
  │ └─┬alert
  │   └──[M] $ref (63211:13)❌
  ├─┬webhook-secret-scanning-alert-resolved
  │ └─┬alert
  │   └──[M] $ref (166393:11)❌
  ├─┬webhook-secret-scanning-alert-location-created
  │ └─┬alert
  │   └──[M] $ref (63211:13)❌
  ├─┬webhook-secret-scanning-alert-created
  │ └─┬alert
  │   └──[M] $ref (63211:13)❌
  └─┬webhook-secret-scanning-alert-revoked
    └─┬alert
      └──[M] $ref (63211:13)❌

Date: 07/29/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 7             | 7
❌  7 Breaking changes out of 7
INFO: Modifications: 5
INFO: Removals: 2
INFO: Breaking Removals: 2
INFO: Breaking Modifications: 5

ERROR: breaking changes discovered