[GitHubAE] Update to 1.1.4 (hash: 1b0afaa3948f022b5774051dd572c5c9) from 1.1.4 (hash: 57a31c088f094c74f44e557fa71e9cce) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/git/commits/{commit_sha}
│ │ └─┬GET
│ │   ├──[M] summary (19829:16)
│ │   └──[M] description (19830:20)
│ ├─┬/repos/{owner}/{repo}/git/refs/{ref}
│ │ └─┬DELETE
│ │   └─┬Parameters
│ │     └──[M] description (20111:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/statuses
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (17986:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/status
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (17944:22)
│ ├─┬/user/starred/{owner}/{repo}
│ │ ├─┬GET
│ │ │ └──[-] description (31588:20)
│ │ └─┬DELETE
│ │   └──[-] description (31649:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (17878:22)
│ ├─┬/repos/{owner}/{repo}/git/ref/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (19952:22)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (17762:22)
│ ├─┬/repos/{owner}/{repo}/subscription
│ │ └─┬GET
│ │   └──[-] description (27381:20)
│ ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
│ │ └─┬GET
│ │   └─┬Parameters
│ │     └──[M] description (17807:22)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}/permission
│ │ └─┬GET
│ │   └──[M] description (17082:20)
│ └─┬/repos/{owner}/{repo}/git/matching-refs/{ref}
│   └─┬GET
│     └─┬Parameters
│       └──[M] description (19909:22)
├──check-run-created
└─┬Components
  └──[-] parameters (197590:7)❌

Date: 06/14/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 14            | 0
components       | 1             | 1
❌ 1 Breaking changes out of 15

ERROR: breaking changes discovered