[GitHubAE] Update to 1.1.4-85b44e1fd5b2db48b1416de6372728c7 from 1.1.4-76f712f29453f51c1c4bd0eea5e73762 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit 4025f0
                                                                                SPEC: extracted 2 commits from history
                                                                                DONE: completed

└─┬Paths
  ├─┬/repos/{owner}/{repo}/stats/contributors
  │ └─┬GET
  │   └──[M] description (27210:20)
  └─┬/repos/{owner}/{repo}/stats/code_frequency
    └─┬GET
      ├──[M] description (27139:20)
      └─┬Responses
        └──[-] codes (27172:11)❌

Date: 01/10/24 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 3             | 1

❌  1 Breaking changes out of 3
INFO: Modifications: 2
INFO: Removals: 1
INFO: Breaking Removals: 1

ERROR: breaking changes discovered