[GitHubAE] Update to 1.1.4 (hash: d791772b4539badc890b300491b7d057current=94a9545cd3dd0d1e846bb8711bb43faa) from 1.1.4 (hash: ) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/pages/builds/{build_id}
│ │ └─┬GET
│ │   └──[-] description (24145:20)
│ ├─┬/user/gpg_keys/{gpg_key_id}
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (194251:9)
│ ├─┬/repos/{owner}/{repo}/pages/builds/latest
│ │ └─┬GET
│ │   └──[-] description (24115:20)
│ ├─┬/user/gpg_keys
│ │ ├─┬GET
│ │ │ └─┬Responses
│ │ │   └─┬200
│ │ │     └──application/json
│ │ └─┬POST
│ │   └─┬Responses
│ │     └─┬201
│ │       └─┬application/json
│ │         └─┬default
│ │           └──[M] value (194251:9)
│ ├─┬/repos/{owner}/{repo}/pages
│ │ └─┬GET
│ │   └──[-] description (23806:20)
│ ├─┬/users/{username}/gpg_keys
│ │ └─┬GET
│ │   └─┬Responses
│ │     └─┬200
│ │       └──application/json
│ └─┬/repos/{owner}/{repo}/pages/builds
│   └─┬GET
│     └──[-] description (24049:20)
└─┬Components
  └─┬simple-commit
    ├─┬author
    │ ├──[-] description (54630:24)
    │ ├─┬email
    │ │ ├──[-] examples (54642:17)
    │ │ ├──[-] format (54640:23)❌
    │ │ └──[-] description (54638:28)
    │ └─┬name
    │   ├──[-] examples (54636:17)
    │   └──[-] description (54633:28)
    ├─┬committer
    │ ├──[-] description (54650:24)
    │ ├─┬email
    │ │ ├──[-] examples (54662:17)
    │ │ ├──[-] format (54660:23)❌
    │ │ └──[-] description (54658:28)
    │ └─┬name
    │   ├──[-] examples (54656:17)
    │   └──[-] description (54653:28)
    ├─┬id
    │ ├──[-] examples (54611:13)
    │ └──[-] description (54609:24)
    ├─┬message
    │ ├──[-] examples (54619:13)
    │ └──[-] description (54616:24)
    ├─┬timestamp
    │ ├──[-] examples (54625:13)
    │ └──[-] description (54621:24)
    └─┬tree_id
      └──[-] description (54614:24)

Date: 05/31/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 6             | 0
components       | 19            | 2
❌ 2 Breaking changes out of 25

ERROR: breaking changes discovered