[GitHubAE] Update to 1.1.4 (hash: bd58e09980ea04313350ef2359e6d048) from 1.1.4 (hash: 1ce7d9199d6765024018bcddfe6e4dc1) Detected Schema changes:
└─┬Paths
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/comments
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (22135:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (22183:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (26923:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels/{name}
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (22531:14)
  ├─┬/repos/{owner}/{repo}/pulls/{pull_number}/comments
  │ └─┬POST
  │   └──[M] description (25055:20)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees
  │ ├─┬POST
  │ │ └─┬External Docs
  │ │   └──[M] url (21998:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (22046:14)
  ├─┬/repos/{owner}/{repo}/issues/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (21732:14)
  ├─┬/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (4277:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (15580:14)
  │ └─┬PATCH
  │   ├─┬External Docs
  │   │ └──[M] url (15611:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (15686:36)
  ├─┬/repos/{owner}/{repo}/issues/comments
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (21401:14)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (23618:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (23708:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (23648:14)
  ├─┬/repos/{owner}/{repo}/check-suites
  │ └─┬POST
  │   ├──[M] description (15954:20)
  │   └─┬External Docs
  │     └──[M] url (15963:14)
  ├─┬/enterprises/{enterprise}/secret-scanning/alerts
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (3210:14)
  ├─┬/repos/{owner}/{repo}/milestones
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (23480:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (23547:14)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-suites
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (17910:14)
  ├─┬/repos/{owner}/{repo}/check-runs
  │ └─┬POST
  │   ├─┬External Docs
  │   │ └──[M] url (15280:14)
  │   └─┬Requestbody
  │     └─┬application/json
  │       └─┬Schema
  │         └─┬output
  │           └─┬annotations
  │             └──[M] description (15362:36)
  ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (21769:14)
  ├─┬/repos/{owner}/{repo}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (13174:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (26966:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (27004:14)
  ├─┬/repos/{owner}/{repo}/issues
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (21181:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (21277:14)
  ├─┬/repos/{owner}/{repo}/assignees
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (13132:14)
  ├─┬/orgs/{org}/issues
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (7244:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/assignees/{assignee}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22099:14)
  ├─┬/repos/{owner}/{repo}/issues/comments/{comment_id}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (21452:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (21530:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (21483:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (15916:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (16084:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22242:14)
  ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (23732:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (22837:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
  │ ├─┬PUT
  │ │ └─┬External Docs
  │ │   └──[M] url (22576:14)
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (22629:14)
  ├─┬/repos/{owner}/{repo}/check-suites/preferences
  │ └─┬PATCH
  │   ├──[M] description (16010:20)
  │   └─┬External Docs
  │     └──[M] url (16021:14)
  ├─┬/repos/{owner}/{repo}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (23029:14)
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (23067:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (21819:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (21855:14)
  ├─┬/repos/{owner}/{repo}/secret-scanning/alerts/{alert_number}/locations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (27066:14)
  ├─┬/repos/{owner}/{repo}/labels/{name}
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (23134:14)
  │ ├─┬DELETE
  │ │ └─┬External Docs
  │ │   └──[M] url (23228:14)
  │ └─┬PATCH
  │   └─┬External Docs
  │     └──[M] url (23168:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/rerequest
  │ └─┬POST
  │   └─┬External Docs
  │     └──[M] url (16176:14)
  ├─┬/repos/{owner}/{repo}/check-runs/{check_run_id}/annotations
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (15875:14)
  ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
  │ ├─┬GET
  │ │ └─┬External Docs
  │ │   └──[M] url (22280:14)
  │ ├─┬PUT
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (22411:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       ├─┬ONEOF
  │ │       │ ├──[M] type (22461:23)❌
  │ │       │ └──[-] properties (22424:19)❌
  │ │       ├─┬ONEOF
  │ │       │ ├──[M] type (22440:23)❌
  │ │       │ └──[+] properties (22442:19)
  │ │       ├─┬ONEOF
  │ │       │ ├──[+] items (22455:19)❌
  │ │       │ ├──[M] type (22452:23)❌
  │ │       │ ├──[+] minItems (22453:27)❌
  │ │       │ └──[-] properties (22442:19)❌
  │ │       └─┬ONEOF
  │ │         ├──[-] items (22455:19)❌
  │ │         ├──[M] type (22422:23)❌
  │ │         ├──[-] minItems (22453:27)❌
  │ │         └──[+] properties (22424:19)
  │ ├─┬POST
  │ │ ├─┬External Docs
  │ │ │ └──[M] url (22322:14)
  │ │ └─┬Requestbody
  │ │   └─┬application/json
  │ │     └─┬Schema
  │ │       ├─┬ONEOF
  │ │       │ ├──[-] items (22349:19)❌
  │ │       │ ├──[M] type (22333:23)❌
  │ │       │ ├──[-] minItems (22347:27)❌
  │ │       │ └──[+] properties (22335:19)
  │ │       ├─┬ONEOF
  │ │       │ ├──[+] items (22349:19)❌
  │ │       │ ├──[M] type (22346:23)❌
  │ │       │ └──[+] minItems (22347:27)❌
  │ │       └─┬ONEOF
  │ │         ├──[M] type (22371:23)❌
  │ │         └──[-] properties (22335:19)❌
  │ └─┬DELETE
  │   └─┬External Docs
  │     └──[M] url (22501:14)
  ├─┬/repos/{owner}/{repo}/check-suites/{check_suite_id}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (16116:14)
  ├─┬/repos/{owner}/{repo}/commits/{ref}/check-runs
  │ └─┬GET
  │   └─┬External Docs
  │     └──[M] url (17845:14)
  └─┬/user/issues
    └─┬GET
      └─┬External Docs
        └──[M] url (30470:14)

Date: 07/14/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 83            | 18
❌ 18 Breaking changes out of 83

ERROR: breaking changes discovered