[GitHubAE] Update to 1.1.4 (hash: 8440de522464f4ce18eb8eae51d0cbeacurrent=d791772b4539badc890b300491b7d057) from 1.1.4 (hash: ) Detected Schema changes:
├─┬Paths
│ ├─┬/repos/{owner}/{repo}/issues/events
│ │ └─┬GET
│ │   └──[-] description (21684:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}
│ │ ├─┬GET
│ │ │ └──[-] description (23561:20)
│ │ └─┬DELETE
│ │   └──[-] description (23651:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (22232:20)
│ │ ├─┬POST
│ │ │ └──[-] description (22273:20)
│ │ └─┬DELETE
│ │   └──[-] description (22453:20)
│ ├─┬/orgs/{org}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (6147:20)
│ ├─┬/users/{username}/projects
│ │ └─┬GET
│ │   └──[-] description (32244:20)
│ ├─┬/repos/{owner}/{repo}/teams
│ │ └─┬GET
│ │   ├──[-] description (27567:20)
│ │   └─┬Responses
│ │     └──[-] codes (197759:7)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/timeline
│ │ └─┬GET
│ │   └──[-] description (22786:20)
│ ├─┬/projects/columns/{column_id}/cards
│ │ └─┬GET
│ │   └──[-] description (10437:20)
│ ├─┬/user/memberships/orgs
│ │ └─┬GET
│ │   └──[-] description (30644:20)
│ ├─┬/repos/{owner}/{repo}/issues/events/{event_id}
│ │ └─┬GET
│ │   └──[-] description (21721:20)
│ ├─┬/repos/{owner}/{repo}/milestones
│ │ ├─┬GET
│ │ │ └──[-] description (23423:20)
│ │ └─┬POST
│ │   └──[-] description (23490:20)
│ ├─┬/repos/{owner}/{repo}/issues
│ │ └─┬POST
│ │   └─┬Responses
│ │     └──[-] codes (197771:7)❌
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/events
│ │ └─┬GET
│ │   └──[-] description (22194:20)
│ ├─┬/repos/{owner}/{repo}/milestones/{milestone_number}/labels
│ │ └─┬GET
│ │   └──[-] description (23675:20)
│ ├─┬/projects/columns/cards/{card_id}
│ │ ├─┬GET
│ │ │ └──[-] description (10081:20)
│ │ └─┬DELETE
│ │   └──[-] description (10175:20)
│ ├─┬/user/memberships/orgs/{org}
│ │ ├─┬GET
│ │ │ └──[-] description (30695:20)
│ │ └─┬PATCH
│ │   └──[-] description (30729:20)
│ ├─┬/projects/columns/{column_id}
│ │ ├─┬GET
│ │ │ └──[-] description (10326:20)
│ │ └─┬DELETE
│ │   └──[-] description (10411:20)
│ ├─┬/repos/{owner}/{repo}/actions/secrets/{secret_name}
│ │ └─┬PUT
│ │   └──[M] description (12683:20)
│ ├─┬/repos/{owner}/{repo}/labels
│ │ ├─┬GET
│ │ │ └──[-] description (22974:20)
│ │ └─┬POST
│ │   └──[-] description (23010:20)
│ ├─┬/repos/{owner}/{repo}/labels/{name}
│ │ ├─┬GET
│ │ │ └──[-] description (23079:20)
│ │ ├─┬DELETE
│ │ │ └──[-] description (23173:20)
│ │ └─┬PATCH
│ │   └──[-] description (23113:20)
│ └─┬/projects/{project_id}/columns
│   ├─┬GET
│   │ └──[-] description (11014:20)
│   └─┬POST
│     └──[-] description (11053:20)
└─┬Components
  └─┬api-overview
    └──[-] properties (50437:9)❌

Date: 06/03/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
paths            | 33            | 2
components       | 1             | 1
❌ 3 Breaking changes out of 34

ERROR: breaking changes discovered