[GitHubAE] Update to 1.1.4-c6744147e855e41e495357d212c83466 from 1.1.4-b989ff83ac81fa58b5ba441c3533ada9 Detected Schema changes:                                                                                 starting work.                                                                                 Building original model for commit dd48ea                                                                                 SPEC: extracted 2 commits from history
                                                                                DONE: completed

WARNING: warnings reported during processing
⚠️  Error thrown when comparing: infinite circular reference detected: repository: installation-token -> repository -> repository [47680:7]
├─┬Paths
│ ├─┬/user/starred/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (31646:20)
│ ├─┬/repos/{owner}/{repo}/actions/workflows/{workflow_id}/runs
│ │ └─┬GET
│ │   └──[M] description (12991:20)
│ ├─┬/orgs/{org}/teams/{team_slug}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (9783:32)
│ ├─┬/orgs/{org}/teams/{team_slug}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (9931:20)
│ ├─┬/teams/{team_id}/projects/{project_id}
│ │ └─┬PUT
│ │   └─┬Requestbody
│ │     └─┬application/json
│ │       └─┬Schema
│ │         └─┬permission
│ │           └──[M] description (29479:32)
│ ├─┬/users/{username}
│ │ └─┬GET
│ │   └──[M] description (31831:20)
│ ├─┬/teams/{team_id}/members/{username}
│ │ └─┬PUT
│ │   └──[M] description (29161:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/attempts/{attempt_number}/jobs
│ │ └─┬GET
│ │   └──[M] description (12258:20)
│ ├─┬/gists/{gist_id}/star
│ │ └─┬PUT
│ │   └──[M] description (4004:20)
│ ├─┬/repos/{owner}/{repo}/collaborators/{username}
│ │ └─┬PUT
│ │   └──[M] description (16937:20)
│ ├─┬/repos/{owner}/{repo}/issues/{issue_number}/lock
│ │ └─┬PUT
│ │   └──[M] description (22511:20)
│ ├─┬/teams/{team_id}/repos/{owner}/{repo}
│ │ └─┬PUT
│ │   └──[M] description (29640:20)
│ ├─┬/user/following/{username}
│ │ └─┬PUT
│ │   └──[M] description (30006:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs/{run_id}/jobs
│ │ └─┬GET
│ │   └──[M] description (12413:20)
│ ├─┬/repos/{owner}/{repo}/actions/runs
│ │ └─┬GET
│ │   └──[M] description (12064:20)
│ └─┬/users/{username}/suspended
│   └─┬PUT
│     └──[M] description (32455:20)
└─┬Components
  ├─┬code-scanning-organization-alert-items
  │ └─┬rule
  │   └──[M] $ref (51918:13)❌
  └─┬code-scanning-alert-rule-summary
    └──[-] properties (51939:9)❌

Date: 12/15/23 | Commit: New: etc/specs/GitHubAE/previous.spec.yaml, Original: etc/specs/GitHubAE/current.spec.yaml
Document Element | Total Changes | Breaking Changes
components       | 2             | 2
paths            | 16            | 0

❌  2 Breaking changes out of 18
INFO: Modifications: 17
INFO: Removals: 1
INFO: Breaking Removals: 1
INFO: Breaking Modifications: 1

ERROR: breaking changes discovered